### ISSUE TITLE
Is this library using blas or fortran libraries for performance?

### ISSUE THREAD

**Issue by mrkaspa** [safwank/Numerix#2]

**Comment by safwank** [comment]
At this point I'd only recommend using this library for small to medium sized datasets. I have plans to optimize it for large datasets at some point, but not in the near future. That said, I welcome PRs.

**Comment by arpieb** [comment]
@safwank have you seen @remiq's [work](https://github.com/remiq/elixir-cuda-example) integrating a CUDA-based Erlang C Node with Elixir?  Might be an interesting approach to sidestep the whole NIF "hang" issue and dealing with Port I/O and provide a more Elixir-like integration to a compute server.

Not sure how well it would work with marshaling large chunks of data...

**Comment by remiq** [comment]
@arpieb Writing C Nodes for a "collection of functions" would be an overkill. Not only because of (re)writing functions in another language and node sync problems, but also compiling it on different machines is complicated. If you have specific problem in mind (ie. that requires a lot of computing power) and you want to maintain it on your machine then maybe it is worth to use C Nodes. Otherwise I wouldn't recommend to use it, especially at production (but I do).
